services:
  mariadb:
    image: mariadb:11
    container_name: haarhartklop-db
    restart: unless-stopped
    environment:
      MARIADB_ROOT_PASSWORD: haarhartklop
      MARIADB_DATABASE: haarhartklop
      MARIADB_USER: haarhartklop
      MARIADB_PASSWORD: haarhartklop
    ports:
      - "3306:3306"
    volumes:
      - mariadbdata:/var/lib/mysql

volumes:
  mariadbdata:
